name: Test CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
